### ISSUE TITLE
Pattern Character Limit

### ISSUE THREAD

**Issue by CassandraSakyubasu** [dodingdaga/DalamudPlugins#10]
Hello ! I was wondering if it was possible to up the limit on the Pattern field to be able to insert more commands ?

**Comment by dodingdaga** [comment]
limit upped from 500 to 1000. also stored now on the plugin settings - not yet editable in the UI but you can edit the plugin config:

`%APPDATA%\XIVLauncher\pluginConfigs\PuppetMaster.json`

`"MaxRegexLength": 1000`
