### ISSUE TITLE
Request: Update for 6.5

### ISSUE THREAD

**Issue by Tihra** [dodingdaga/DalamudPlugins#12]
I discovered this plugin a few hours before the update to 6.5.

As the code seems to be private I cannot update it myself in a personal fork.
What is the liklihood of this plugin being updated or the code being made public?
I can't find a way to contact you via discord.

**Comment by VerdantKozak** [comment]
You should add your own contact info inside of your comment!

**Comment by Tihra** [comment]
Ah I understand your intention but I'd rather not post that in a public space. This "Issue" is just a question.

**Comment by guppyfaced** [comment]
getting your friend to self destruct is a vital game-play feature!

**Comment by VerdantKozak** [comment]
It is!!

**Comment by Mooncubus** [comment]
I am also throwing my hat in pleading for a 6.5 update. I only just heard about this plugin and am sad I can't even try it now

**Comment by Tihra** [comment]
If the code was public or the repo for it was known, I'd be happy to update it in another fork for dodingdaga.

**Comment by dodingdaga** [comment]
Hi all! Been busy with werk. 😭 Updated for 6.5 now

**Comment by Tihra** [comment]
Amazing!

**Comment by dodingdaga** [comment]
RBAY  just updated!
