### ISSUE TITLE
Feature Request: potentially allow "do follow".

### ISSUE THREAD

**Issue by EstoyMejor** [dodingdaga/DalamudPlugins#2]
When you are in a party the game allows you to right click and then "Follow". 
If theres any way to implement that into this plugin this would be insanely nice <3

**Comment by dodingdaga** [comment]
This is possible with the latest version. You can enable "Allow all text commands". And in the party chat, you can do <triggerphrase> (ac target [2]) to target the party leader. and then do <triggerphrase (follow)

**Comment by EstoyMejor** [comment]
Ooh? Okay then I was apparently just too stupid.

**Comment by dodingdaga** [comment]
No worries! You can check all the available text commands from the in game macros menu. Just need to convert the syntax. In case command has subcommands you can put them in parentheses and replace `<> `with `[]` for placeholders

**Comment by EstoyMejor** [comment]
Works perfectly! I used simple tweaks to even enable old /target (Name) and now they have a macro focusing them and follow and it works super reliable! Thank youuuuu!
