### ISSUE TITLE
Cannot use items with quotes in the names

### ISSUE THREAD

**Issue by SaloBen-ff** [dodingdaga/DalamudPlugins#21]
I'm trying use an item that has a quote in the name, but its stripping off the end parenthesis. 

/channel Key (use Magicked Prism ("Meteor Survivor")

but the character is showing they only get 
/channel key (use Magicked Prism ("Meteor Survivor"

This isn't a bug, but my lack of knowledge of regex. I couldn't find a place to ask a question for support, so i am hoping to find help here.

Thank you!

**Comment by dodingdaga** [comment]
hi! this is caused by the non-greedy matching for characters within the parenthesis.
You can enable regex and change the trigger to (assuming the keyword is "key"):

`(?i)\b(?:key)\s+(?:\((.*)\)|(\w+))`

**Comment by dodingdaga** [comment]
![image](https://github.com/user-attachments/assets/f9acb933-ea2b-4a91-9605-74ad5b71462a)

**Comment by SaloBen-ff** [comment]
Works perfectly now. Thank you  :)
