### ISSUE TITLE
Not working since 7.1

### ISSUE THREAD

**Issue by XenonKaguno** [dodingdaga/DalamudPlugins#22]
Plugin current isn't working since 7.1 are there any plans to update it?

**Comment by MoonTakashi** [comment]
Please update it! We need this back online!! Y~Y

**Comment by AthenaTaso** [comment]
I've put up a PR to update it to API 11, Hopefully the owner will accept it and yall will be back in business.

**Comment by dodingdaga** [comment]
omg hi!! thank you @AthenaTaso!!! ill check it. just going thru life.  i forgot there's an update 🧀

**Comment by AthenaTaso** [comment]
@dodingdaga no problem! if i can do anything else to help feel free to reach out <3

**Comment by dodingdaga** [comment]
Puppetmaster should be okay now. Just testing Copycat.
