### ISSUE TITLE
Feature request: expand on how the "any command" command and arguments are passed/used

### ISSUE THREAD

**Issue by someMinecrafter** [dodingdaga/DalamudPlugins#7]
Currently you need to do: trigger (command argument1 argument2 ... ) with parentheses, if I've not misunderstood.
Now with regex, you would be able to specify which group corresponds to what (you can also name the groups in regex, but that might be overkill).

Example input that I'd like to be able to use: trigger command argument1 argument2 ...
Example 2: !command trigger, -argument1 -argument2

**Comment by dodingdaga** [comment]
oh yes! I'll add this to my queue.
This will allow customizing how the full command syntax will be sent to the game based on the groups defined (right now it's just prepending "/" to the command group that was set).

**Comment by dodingdaga** [comment]
Added customization in latest version (1.6.7) Named groups supported.
May click "Reset" to re-initialize the regex pattern and replacement based on the "non-regex" simple trigger phrases
