### ISSUE TITLE
list of the commands/prefix

### ISSUE THREAD

**Issue by Blaizey** [dodingdaga/DalamudPlugins#9]

**Comment by manuleko** [comment]
Would like a documentation of available commands..
till now been fiddling with it trying to guess has been hard to know what you can and cannot do
Specially on targetting, if it's possible to target someone else, or make it target yourself.

**Comment by Aspher0** [comment]
You can open the in game's emote menu to check what are the emotes commands, also you can check every base game commands on the lodestone (Exemple: https://na.finalfantasyxiv.com/lodestone/playguide/db/text_command/)
And for 3rd party plugins, you just have to know them.
PuppetMaster does not add any command in the game besides its own.

**Comment by dodingdaga** [comment]
For 3rd party plugins. you can try `/xldata` and select  Commands
